gcp_credentials = "/home/jonathan/Desktop/Compound-Interest-GCP-Infrastructure/direct-keel-400715-e678966f1112.json"
gcp_project_id = "direct-keel-400715"
gcp_region = "us-west1"
gke_cluster_name = "compound-interest-prod"
gke_zones = [ "us-west1-a" ]
gke_network = "default"
gke_subnetwork = "default"
gke_default_nodepool_name = "compound-interest-node"
gke_service_account_name = "terraform-sa@direct-keel-400715.iam.gserviceaccount.com"