gcp_credentials = "/home/jonathan/Desktop/Compound-Interest-GCP-Infrastructure/compound-interest-project-b2d2d9d02e18.json"
gcp_project_id = "compound-interest-project"
gcp_region = "us-west1"
gke_cluster_name = "compound-interest-prod"
gke_zones = [ "us-west1-a" ]
gke_network = "default"
gke_subnetwork = "default"
gke_default_nodepool_name = "compound-interest-node"
gke_service_account_name = "terraform-sa@compound-interest-project.iam.gserviceaccount.com"